sudo: required
services:
  - docker

#before_install:
#  - docker build -t arunciman/fib-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run arunciman/fib-test npm test -- --coverage
  - docker build -t arunciman/fib-worker ./worker
  - docker build -t arunciman/fib-nginx ./nginx
  - docker build -t arunciman/fib-server ./server
  - docker build -t arunciman/fib-client ./client
  # Take images and push to cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arunciman/fib-client
  - docker push arunciman/fib-worker
  - docker push arunciman/fib-nginx
  - docker push arunciman/fib-server

  deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-218844036683
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY